branches:
    only:
        master

stages:
    - lint
    - test

language: python
python:
- '3.6'

install:
    - pip install -r requirements/dev.txt

jobs:
    include:
        - stage: "lint"
          name: "flake8"
          script:
              - flake8 .
        - stage: "test"
          name: "Unit Tests"
          script:
              - python -m unittest discover tests
