branches:
    only:
        master

stages:
    - test

language: python
python:
- '3.6'

install:
    - pip install -r requirements/base.txt

jobs:
    include:
        - stage: "test"
          name: "Download and Sync screens test"
          script:
              - python -m unittest download_screens/test_download_screens.py
              - python -m unittest screens_manager/test_screens_manager.py
