branches:
    only:
        master

stages:
    - lint
    - test

language: python
python:
- '3.6'

install:
    - pip install -r requirements/ci.txt

jobs:
    include:
        - stage: "lint"
          name: "flake8"
          script:
              - flake8 .
        - stage: "test"
          name: "Unit Tests"
          script:
              - nosetests tests --with-coverage

after_success:
    - codecov
